### ISSUE TITLE
Support more association resources

### ISSUE THREAD

**Issue by magodo** [magodo/aztft#7]
With `cat internal/resmap/map.json| jq -r '. | select( keys[] | endswith("_association"))'`, I get:

- azurerm_monitor_data_collection_rule_association
- azurerm_nat_gateway_public_ip_association (supported)
- azurerm_nat_gateway_public_ip_prefix_association (supported)
- azurerm_network_interface_application_gateway_backend_address_pool_association (supported)
- azurerm_network_interface_application_security_group_association (supported)
- azurerm_network_interface_backend_address_pool_association (supported)
- azurerm_network_interface_nat_rule_association (supported)
- azurerm_network_interface_security_group_association (supported)
- azurerm_spring_cloud_app_cosmosdb_association (is a concrete azure resource)
- azurerm_spring_cloud_app_mysql_association (is a concrete azure resource)
- azurerm_spring_cloud_app_redis_association (is a concrete azure resource)
- azurerm_subnet_nat_gateway_association (is a concrete azure resource)
- azurerm_subnet_network_security_group_association
- azurerm_subnet_route_table_association
- azurerm_virtual_desktop_workspace_application_group_association (supported)

With `cat internal/resmap/map.json| jq -r '. | keys[] | select(. | endswith("_attachment"))'`, I get:

- azurerm_disk_pool_managed_disk_attachment (supported)
- azurerm_virtual_machine_data_disk_attachment (supported)

So approximately, we have following property-like resources left to be supported:

- [x] azurerm_subnet_nat_gateway_association (#8)
- [x] azurerm_subnet_network_security_group_association (#8)
- [x] azurerm_subnet_route_table_association (#8)

**Comment by magodo** [comment]
Closed by #8

**Comment by vanmash** [comment]
hey @magodo 
Any chances for adding support for `azurerm_monitor_data_collection_rule_association`?

**Comment by vanmash** [comment]
--> https://github.com/magodo/aztft/issues/16
